runai:
  name: inference-workload

  containers:
    imagePullPolicy: Always
    name: inference-workload
    ports:
      containerPort: 80

  schedulerName: default 

  service:
    name: runai-service
    type: ClusterIP
    protocol: TCP
    port: 80
    targetPort: 80
    
  route:
    name: runai-route

replicaCount: 2
namespace: runai-namespace
image: gcr.io/run-ai-demo/quickstart
gpu: 1
user: yuval