apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.runai.route.name }}
  namespace: {{ .Values.namespace }}
spec:
  port:
    targetPort: {{ .Values.runai.service.targetPort }} 
  to:
    kind: Service
    name: {{ .Values.runai.service.name }}