apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.runai.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.runai.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.runai.name }}
        user: {{ .Values.user }}
    spec:
      containers:
      - name: {{ .Values.runai.containers.name }}
        image: {{ .Values.image }}
        resources:
          limits:
            nvidia.com/gpu: {{ .Values.gpu }}
        imagePullPolicy: {{ .Values.runai.containers.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.runai.containers.ports.containerPort }}
