apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.runai.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.runai.name }}
spec:
  type: {{ .Values.runai.service.type }}
  ports:
    - port: {{ .Values.runai.service.port }}
      targetPort: {{ .Values.runai.service.targetPort }}
      protocol: {{ .Values.runai.service.protocol }}
  selector:
    app: {{ .Values.runai.name }}
    user: {{ .Values.user }}

