apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.runai.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.runai.name }}
      nodeType: {{ .Values.runai.affinity.value }}
  template:
    metadata:
      labels:
        nodeType: {{ .Values.runai.affinity.value }}
        app: {{ .Values.runai.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.runai.affinity.key }}
                operator: {{ .Values.runai.affinity.operator }}
                values: 
                - {{ .Values.runai.affinity.value }}
      containers:
      - name: {{ .Values.runai.containers.name }}
        image: {{ .Values.image }}
        resources:
          limits:
            nvidia.com/gpu: {{ .Values.gpu }}
        imagePullPolicy: {{ .Values.runai.containers.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.runai.containers.ports.containerPort }}
      schedulerName: {{ .Values.runai.schedulerName }}   
